# Generated by Django 4.0.2 on 2022-02-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='numero',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
