# Generated by Django 4.0.2 on 2022-02-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_alter_curso_carga_horaria'),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='curso.curso'),
        ),
    ]
