# Generated by Django 4.0.2 on 2022-02-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_curso_link_alter_curso_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(),
        ),
    ]
